destination: docs/
#baseurl: '127.0.0.1:4000'
permalink: pretty
title: 'ÖGT - Österreichische Gesellschaft für Tuina'

logo:
  mobile: "images/logo/logo.gif"
  mobile_height: "32px"
  mobile_width: "35px"
  desktop: "images/logo/logo.gif"
  desktop_height: "68px"
  desktop_width: "75px"

collections:
  absolventen:
    output: true
  team:
    output: true
  events:
    output: true
    permalink: /event/:path/

defaults:
  - scope:
      path: ""
      type: "absolventen"
    values:
      layout: "absolvent"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"

sass:
  indentWidth: 4
  style: compressed # possible values: nested expanded compact compressed
  precision: 10

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
